name: scriber
description: Scriber is a simple and intuitive Notes app built with Flutter and Firebase for iOS and Android.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  # Firebase Plugins
  cloud_firestore: ^4.8.2
  firebase_app_check: ^0.1.5
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_crashlytics: ^3.3.3
  firebase_dynamic_links: ^5.3.3
  
  # Dart/FlutterDev/Google Plugins
  google_sign_in: ^6.1.4
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.11
  intl: ^0.18.1

  # Misc. Community Plugins
  equatable: ^2.0.5
  flex_color_scheme: ^7.1.2
  hooks_riverpod: ^2.3.6
  flutter_hooks: ^0.18.6
  lottie: ^2.4.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0

  # Tests plugins
  google_sign_in_mocks: ^0.3.0
  firebase_auth_mocks: ^0.11.0
  fake_cloud_firestore: ^2.4.1+1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  patrol: ^2.0.3

patrol:
  app_name: Scriber
  android:
    package_name: com.akabo.scriber
  ios:
    bundle_id: com.akabo.scriber
  

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lotties/

    # Add Nunito font from the fonts directory to the application.
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-VariableFont_wght.ttf